// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniCoreEnriqueMerizalde.Migrations
{
    [DbContext(typeof(DbContextMinicore))]
    [Migration("20250420173900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniCoreEnriqueMerizalde.Models.Empleado", b =>
                {
                    b.Property<int>("Id_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empleado"));

                    b.Property<string>("Apellido_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Empleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("MiniCoreEnriqueMerizalde.Models.Proyecto", b =>
                {
                    b.Property<int>("Id_Proyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proyecto"));

                    b.Property<string>("Nombre_Proyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Proyecto");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("MiniCoreEnriqueMerizalde.Models.Tarea", b =>
                {
                    b.Property<int>("Id_Tarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tarea"));

                    b.Property<string>("Descripcion_Tarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Tarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Inicio_Tarea")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_EmpleadoV")
                        .HasColumnType("int");

                    b.Property<int>("Id_ProyectoV")
                        .HasColumnType("int");

                    b.Property<int>("Tiempo_Estimado_Tarea")
                        .HasColumnType("int");

                    b.HasKey("Id_Tarea");

                    b.HasIndex("Id_EmpleadoV");

                    b.HasIndex("Id_ProyectoV");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("MiniCoreEnriqueMerizalde.Models.Tarea", b =>
                {
                    b.HasOne("MiniCoreEnriqueMerizalde.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Id_EmpleadoV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCoreEnriqueMerizalde.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("Id_ProyectoV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });
#pragma warning restore 612, 618
        }
    }
}
